name: Install
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up openJDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '14'
      - name: Build with gradle
        run: make build
